### ISSUE TITLE
Unable to change theme background image

### ISSUE THREAD

**Issue by iceceecc** [Kalyvara/NXTheme-releases#3]
Hello Thank you very much for your theme, I want to change the background image of the theme but when I try I find that it doesn't change I made the theme using Switch theme injector after I passed the Switch theme injector EXTRACT NXTHEME json type file and it doesn't change the background image of your theme I can change the background image of your theme with this method. I can change the wallpaper of other themes with this method. 
Can you change the background image of your theme or am I doing something wrong?

**Comment by iceceecc** [comment]
I am using your CHROMA - Aqua Breeze Edition

**Comment by Kalyvara** [comment]
Hi,
In the JSON of each applet you need to remove the following at the very start of each file

```json
        {
            "FileName": "blyt/BgNml.bflyt",
            "Patches": [
                {
                    "PaneName": "P_Bg_00",
                    "Visible": true,
                    "Position": {
                        "Y": 0
                    },
                    "Size": {
                        "X": 1280,
                        "Y": 720
                    },
                    "UsdPatches": [
                        {
                            "PropName": "C_W",
                            "PropValues": [
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            "type": 1
                        }
                    ],
                    "ColorTL": "FF2f1909",
                    "ColorTR": "FF2f1909",
                    "ColorBL": "FF1a0e05",
                    "ColorBR": "FF1a0e05"
                }
            ]
        },
```

You can then rebuild the nxthemes with the modified layouts

**Comment by iceceecc** [comment]
Thanks for the reply I can change the background for now.
May I ask you one more question? 
I read https://github.com/zzzribas/Patterns/wiki
In this article, it asks to replace blyt/BgNml.bflyt in the menu JSON, but I can't find the blyt/BgNml.bflyt code. 
Thank you for any help you can give me.

**Comment by Kalyvara** [comment]
If you're editing JSON files I'd recommend using a proper text editor like Visual Studio Code. This will highlight relevant parts of the code which makes things exceptionally easier.

As for your question I don't know the specifics of this theme, but given the nature of it it is definitely there. A quick `CTRL+F` (search) should help you find the BgNml.bflyt section. For further info your best bet would be asking zhi himself

**Comment by iceceecc** [comment]
I use this https://themezer.net/themes/homemenu/PS5-Home-Menu-Final-24bf
I extracted the josn using EXTRACT NXTHEME from the switch theme Injector, but strangely, I didn't find the BgNml.bflyt code.　
I'm using Visual Studio Code and I can't find it using search.
Here is the josn file I extracted.
[layout.json](https://github.com/Kalyvara/NXTheme-releases/files/13326211/layout.json)
![}Y7PNX`({2UNZTQ$H0C9D}V](https://github.com/Kalyvara/NXTheme-releases/assets/132486970/34fa914e-768c-4c3b-b0d1-ca5479824b27)

**Comment by Kalyvara** [comment]
Should I understand that you want to keep the PS5 layout and implement the animated background in it? If the `BgNml.bflyt` field isn't present already, simply add it to the PS5 layout, as per zhi's instructions in his tutorial (the one you previously linked). What this does is it overrides the vanilla styling for the `BgNml.bflyt` UI element - if it's not there, then nothing happens.

Please consider reaching out to zhi as I'm not fully aware of the intricacies of his theme

**Comment by iceceecc** [comment]
Thank you very much.

**Comment by Kalyvara** [comment]
To better understand how Switch themes work you might want to refer to the documentation, it's a bit overwhelming but still a valuable resource: https://layoutdocs.themezer.net/guide/
